### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [josenk/vagrant-vmware-esxi#141]
Getting an installation error about `nokogiri`:

`
Building nokogiri using system libraries.
checking for gzdopen() in -lz... yes
checking for xmlParseDoc() in -lxml2... no
checking for xmlParseDoc() in -llibxml2... no
checking for libxml-2.0 using `pkg_config`... no
Please install either the `pkg-config` utility or the `pkg-config` rubygem.
checking for xmlParseDoc() in -lxml2... no
checking for xmlParseDoc() in -llibxml2... no
-----
extconf.rb:285:in `ensure_package_configuration'
extconf.rb:648:in `<main>'
xml2 is missing. Please locate mkmf.log to investigate how it is failing.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
`

**Comment by josenk** [comment]
looks like a nokogiri problem.   They might have forgotten to include xml2 as a dependency.   Have you retried this since the original attempt?

**Comment by Marshall-Hallenbeck** [comment]
Yeah I ended up giving up, couldn't get it to work. It worked outside of the Vagrant environment, but using Vagrant to install the plugin fails with this every time. Tried to build it outside the Vagrant environment and copy it in as well, with no luck.

**Comment by duncanxdc** [comment]
same error
