### ISSUE TITLE
VM Clone Fails

### ISSUE THREAD

**Issue by jbregman** [josenk/vagrant-vmware-esxi#30]
**Host OS:**  Mac OSX 10.12.6 
**Plugin Version:** 2.1.0
**Vagrant Version:**  2.0.1

I'm trying to clone an existing VM.  Here's a snippet from my Vagrantfile

```
    windows_victim.vm.provider :vmware_esxi do |esxi, override|

	#Need this to make SSH work, but for rsync you also need to update ~/.ssh/config
         override.ssh.extra_args = '-oHostKeyAlgorithms=+ssh-dss'
		
    	#  REQUIRED!  ESXi hostname/IP
    	esxi.esxi_hostname = "#{ENV['ESX_SERVER_IP']}"
    	
    	#esxi.esxi_resource_pool = "/"
    	esxi.debug = 'true ip vmx'

    	#  ESXi username
    	esxi.esxi_username = 'root'
    	esxi.esxi_password = 'env:ESX_PASSWORD'
    	esxi.esxi_disk_store = 'volume1'
    
	esxi.guest_name_prefix = 'windows-victim-'	
    	esxi.clone_from_vm = 'windows-victim'
 
  
    end
```

When I run ``vagrant up`` I get the following exception:

```
/Users/josh.bregman/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.1.0/lib/vagrant-vmware-esxi/action/createvm.rb:90:in `read': no implicit conversion of nil into String (TypeError)
	from /Users/josh.bregman/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.1.0/lib/vagrant-vmware-esxi/action/createvm.rb:92:in `createvm'
	from /Users/josh.bregman/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.1.0/lib/vagrant-vmware-esxi/action/createvm.rb:16:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/josh.bregman/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.1.0/lib/vagrant-vmware-esxi/action/read_state.rb:64:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/josh.bregman/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.1.0/lib/vagrant-vmware-esxi/action/esxi_password.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:227:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:202:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:631:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	from /opt/vagrant/embedded/gems/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```
Looks like the issue is that when the OVF tool runs:

```
Writing VMX file: /var/folders/nx/y_rbqrbn1l13h8ml2kr_hnj0pw01l0/T/d20180413-6349-ft9aqe/windows-victim.vmwarevm/windows-victim.vmx
```

The name of the file is <vm_name>.vmwarevm/<vm_name>.vmx.  The code on line 90 isn't adding the .vmwarevm extension.  I'm not sure under what conditions this .vmwarevm gets added, so not sure how to "fix it".

**Comment by josenk** [comment]
Do you use any resource pools to store the source or target?  Or everything is in the root?

Can you try putting a slash in front of your source...
esxi.clone_from_vm = '/windows-victim'

**Comment by josenk** [comment]
I'm pretty sure I found the problem.   I disabled an ovftool option to use "MacNaming", but I have no way to test it for sure.  (I don't have a mac...).

If you could please test this beta, it would be appreciated.   Just uninstall the old plugin, and install this beta.    Let me know how it works out...

$ wget https://dc002.jintegrate.co:/747383237437/vagrant-vmware-esxi-2.2.1beta.gem
$ vagrant plugin uninstall vagrant-vmware-esxi
$ vagrant plugin install vagrant-vmware-esxi-2.2.1beta.gem

**Comment by jbregman** [comment]
That works 👍 

You can see the change in the filename:

```
VMware ovftool 4.2.0 (build-5965791)
ovftool command: ovftool --noSSLVerify --overwrite --X:useMacNaming=false --powerOffTarget --noDisks --targetType=vmx  vi://root:******@192.168.10.4/unix-victim /var/folders/nx/y_rbqrbn1l13h8ml2kr_hnj0pw01l0/T/d20180415-15864-so6scu
Opening VI source: vi://root@192.168.10.4:443/unix-victim
Opening VMX target: /var/folders/nx/y_rbqrbn1l13h8ml2kr_hnj0pw01l0/T/d20180415-15864-so6scu
Writing VMX file: /var/folders/nx/y_rbqrbn1l13h8ml2kr_hnj0pw01l0/T/d20180415-15864-so6scu/unix-victim/unix-victim.vmx
```

We'll keep using this version until 2.2.1 goes GA
