### ISSUE TITLE
set_esxi_password: undefined method `gsub' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by antonipx** [josenk/vagrant-vmware-esxi#38]
Vagrant 2.0.2

```
vagrant up ubuntu_e  --provider=vmware_esxi

/home/as/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-esxi-2.2.1/lib/vagrant-vmware-esxi/action/esxi_password.rb:110:in `set_esxi_password': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /home/as/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-esxi-2.2.1/lib/vagrant-vmware-esxi/action/esxi_password.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
	from /home/as/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-esxi-2.2.1/lib/vagrant-vmware-esxi/provider.rb:24:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:514:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:145:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:694:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:186:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/commands/up/command.rb:87:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/cli.rb:46:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:269:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:151:in `<main>'

```

**Comment by josenk** [comment]
Found the issue...   If esxi_password is unspecified or NIL in Vagrantfile, then it crashes.   This will be fixed in the next release.    In the mean time, just specify the esxi_password option in your Vagrantfile.

**Comment by antonipx** [comment]
By all means I have esxi_password defined in Vagrantfile. I have tried full string as well as prompt:. See attached Vagrantfile.

[Vagrantfile.txt](https://github.com/josenk/vagrant-vmware-esxi/files/1981211/Vagrantfile.txt)

**Comment by josenk** [comment]
By the looks of your Vagrantfile, it looks like you are trying to do multi-machines, but it's not quite right.   You may want to look at my Multi-machine example and the Vagrant documentation.

[https://github.com/josenk/vagrant-vmware-esxi/wiki/Vagrantfile-example:--Multi-machine,-essential-options-only.-(documentation-removed)](https://github.com/josenk/vagrant-vmware-esxi/wiki/Vagrantfile-example:--Multi-machine,-essential-options-only.-(documentation-removed))
[https://www.vagrantup.com/docs/multi-machine/](https://www.vagrantup.com/docs/multi-machine/)

The next release will prevent the ruby crash, but you'll still need to fix your Vagrantfile for expected functionality.

**Comment by antonipx** [comment]
Actually I'm just trying a single VM. Please see attached new Vagrant file.
[Vagrantfile.txt](https://github.com/josenk/vagrant-vmware-esxi/files/1985611/Vagrantfile.txt)
