### ISSUE TITLE
undefined method `fire_triggers' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CrashSpooky** [josenk/vagrant-vmware-esxi#39]
Hi there, I'm seeing this issue on both Mac OSX & CentOS. Clean install of Vagrant on both. Tried a few permutations on the Vagrantfile including the default single VM one from the examples.

```
/opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/machine.rb:164:in `action': undefined method `fire_triggers' for nil:NilClass (NoMethodError)
	from /home/user01/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.2.1/lib/vagrant-vmware-esxi/provider.rb:24:in `state'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/machine.rb:521:in `state'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/machine.rb:145:in `initialize'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/vagrantfile.rb:79:in `new'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/environment.rb:700:in `machine'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/plugin/v2/command.rb:186:in `each'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/commands/up/command.rb:87:in `execute'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/cli.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/environment.rb:275:in `cli'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/bin/vagrant:156:in `<main>'
```

```
[user01@deploy01 ~]$ vagrant --version
Vagrant 2.1.0
```
```
[user01@deploy01 ~]$ ovftool --version
VMware ovftool 4.3.0 (build-7948156)
```

**Comment by josenk** [comment]
This is a known bug with the Vagrant 2.1.0.
 https://github.com/hashicorp/vagrant/issues/9775

I was able to reproduce it on any of my machines running Vagrant 2.1.0   My development machine running Vagrant 2.1.1.dev works fine. 

For now you'll have to install Vagrant 2.0.4 or wait for 2.1.1 to be released.
