### ISSUE TITLE
Machine does not start during multiple deployment

### ISSUE THREAD

**Issue by shashial** [josenk/vagrant-vmware-esxi#45]
So, one machine does not start during multiple(2) deployment.

Vagrant version:

```
Installed Version: 2.1.1
Latest Version: 2.1.1
You're running an up-to-date version of Vagrant!
```

lsb_resease
```
Description:    Linux Mint 18 Sarah
```

Vagrantfile:
```
nodes = [
  { hostname: 'VM-multi1', box: 'opentable/win-2012r2-standard-amd64-nocm' },
  { hostname: 'VM-multi2', box: 'opentable/win-2012r2-standard-amd64-nocm' }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.hostname = node[:hostname]
      node_config.vm.box = node[:box]
      node_config.vm.communicator = "winrm"
      node_config.winrm.username = "vagrant"
      node_config.winrm.password = "vagrant"
      node_config.vm.provision "shell", inline: "mkdir c:\\test"
      node_config.vm.provision :shell, :path => "./provision.ps1"
    end
  end

  config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = 'ip address'
    esxi.esxi_username = 'username'
    esxi.esxi_password = 'qwerty'
    esxi.debug = 'true'
  end
end
```

Error happens here:
```
==> VM-multi1: --- VM has been Powered On...
==> VM-multi2: --- VM has been Powered On...
==> VM-multi1: --- Waiting for state "running"
==> VM-multi2: --- Waiting for state "running"
==> VM-multi1: --- Success, state is now "running"
num adapters: 1,  vm.network.count: 0
==> VM-multi2: --- Success, state is now "running"
num adapters: 1,  vm.network.count: 0
==> VM-multi1: Setting hostname...
==> VM-multi2: Setting hostname...
**==> VM-multi2: An error occurred. The error will be shown after all tasks complete.**
==> VM-multi1: Running provisioner: shell...

```

Error text:

```
An unexpected error occurred when executing the action on the
'VM-multi2' machine. Please report this as a bug:

Bad HTTP response returned from server. Body(if present): (500).

/opt/vagrant/embedded/gems/2.1.1/gems/winrm-2.2.3/lib/winrm/http/response_handler.rb:90:in `raise_transport_error'
/opt/vagrant/embedded/gems/2.1.1/gems/winrm-2.2.3/lib/winrm/http/response_handler.rb:54:in `raise_if_error'
/opt/vagrant/embedded/gems/2.1.1/gems/winrm-2.2.3/lib/winrm/http/response_handler.rb:36:in `parse_to_xml'
/opt/vagrant/embedded/gems/2.1.1/gems/winrm-2.2.3/lib/winrm/http/transport.rb:186:in `send_request'
/opt/vagrant/embedded/gems/2.1.1/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:44:in `close_shell'
/opt/vagrant/embedded/gems/2.1.1/gems/winrm-2.2.3/lib/winrm/shells/base.rb:90:in `close'
/opt/vagrant/embedded/gems/2.1.1/gems/winrm-2.2.3/lib/winrm/connection.rb:46:in `ensure in shell'
/opt/vagrant/embedded/gems/2.1.1/gems/winrm-2.2.3/lib/winrm/connection.rb:46:in `shell'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/communicators/winrm/shell.rb:58:in `powershell'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/communicators/winrm/communicator.rb:148:in `execute'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/windows/cap/reboot.rb:12:in `wait_for_reboot'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/capability_host.rb:111:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/capability_host.rb:111:in `capability'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/guest.rb:43:in `capability'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/windows/cap/change_host_name.rb:32:in `change_host_name_and_wait'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/windows/cap/change_host_name.rb:7:in `change_host_name'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/capability_host.rb:111:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/capability_host.rb:111:in `capability'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/guest.rb:43:in `capability'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builtin/set_hostname.rb:21:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/home/nekto/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/read_state.rb:64:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/home/nekto/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/read_state.rb:64:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/home/nekto/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/esxi_password.rb:18:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/home/nekto/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/set_network_ip.rb:20:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/home/nekto/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/boot.rb:16:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/home/nekto/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/read_state.rb:64:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/home/nekto/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/createvm.rb:19:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/home/nekto/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/read_state.rb:64:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/home/nekto/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/esxi_password.rb:18:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:239:in `action_raw'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:208:in `block in action'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:598:in `lock'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:194:in `call'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:194:in `action'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
/opt/vagrant/embedded/gems/2.1.1/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by josenk** [comment]
This is a Vagrant problem (and/or a buggy box)...   Vagrant is using winrm to update the hostname.  The bug is there.  My plugin doesn't actually update hostnames, vagrant does that part...   If vm.hostname is set, I call the vagrant code to update the hostname.   If it's not set, then that code is not run.

There are a number of ways to doing Multi-machines.   Here is one way that makes it a easier to enable/disable the vm.hostname option.     Try this Vagrantfile (with vm.hostname remarked out) and the build should work...

```
nodes = [
  { hostname: 'VM-multi1', box: 'opentable/win-2012r2-standard-amd64-nocm' },
  { hostname: 'VM-multi2', box: 'opentable/win-2012r2-standard-amd64-nocm' }
]
Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      #node_config.vm.hostname = node[:hostname]
      node_config.vm.box = node[:box]
      node_config.vm.communicator = "winrm"
      node_config.winrm.username = "vagrant"
      node_config.winrm.password = "vagrant"
      node_config.vm.provision "shell", inline: "mkdir c:\\test"
      node_config.vm.provision :shell, :path => "./provision.ps1"

      config.vm.provider :vmware_esxi do |esxi|
        esxi.esxi_hostname = 'ip address'
        esxi.esxi_username = 'username'
        esxi.esxi_password = 'qwerty'
        esxi.guest_name = node[:hostname]
        esxi.debug = 'true'
      end
    end
  end
end
```

You have a couple of choices.
1) Don't set vm.hostname
2) File a bug report to Hashicorp/Vagrant
3) There is something in that box that's causing the sethostname to fail.   You need to figure that out, then fix the box.  (This is a similar issue to generic/centos7)
