### ISSUE TITLE
Error: Invalid target disk adapter type: pvscsi

### ISSUE THREAD

**Issue by johnoooo** [josenk/vagrant-vmware-esxi#46]
I want to create an own base box for some of my deployments. For that 
1. I manually create a VM on my ESXi host (CentOS 7.5.1804 Minimal) 
2. clone from it using `vagrant-vmware-esxi` to make it managed by vagrant, apply my modifications using setup scripts and eventually have my BaseBox 

### Step 1: The manually created box
The options when creating the initial box:
* Name: CentOSBaseSCSI2
* Guest OS Family: Linux
* Guest OS Type: CentOS 7 (64 Bit)
* HDD 64GB thin provisioned which is attached to the SCSI adapter (the default)
* Installation ISO image connected to the CD drive

The OS doesn't even have to be installed. The problem below does not depend on that

### Step 2: Cloning from this initial box

I use the following vagrant file, which is derived from the example for cloning from an existing VM
```
Vagrant.configure('2') do |config|

  config.vm.box = 'vmware_esxi/dummy'

  config.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)

  config.vm.provider :vmware_esxi do |esxi|

        esxi.esxi_hostname = 'esxi02'
        esxi.esxi_username = 'root'
        esxi.esxi_password = 'xxxxxxxx'

        esxi.clone_from_vm = 'myCentOSBaseSCSI2'
        esxi.esxi_resource_pool = "/"

        esxi.debug = 'true ip vmx' # 'true ip vmx'

  end
end
```

### The Error
and run a `vagrant up` which results in 
```
RUBY_PLATFORM: x86_64-linux
Testing esxi connectivity
==> default: --- ESXi version    : VMware ESXi 6.7.0 build-8169922
Bringing machine 'default' up with 'vmware_esxi' provider...
==> default: Virtual Machine will be built.
VMware ovftool 4.3.0 (build-7948156)
ovftool command: ovftool --noSSLVerify --overwrite --X:useMacNaming=false --powerOffTarget --noDisks --targetType=vmx --X:logLevel=info --X:logFile=/tmp/d20180619-3507-11ypihh/ovftool.log --acceptAllEulas vi://root:******@esxi02/myCentOSBaseSCSI2 /tmp/d20180619-3507-11ypihh
Opening VI source: vi://root@192.168.0.12:443/myCentOSBaseSCSI2
Opening VMX target: /tmp/d20180619-3507-11ypihh
Error: Invalid target disk adapter type: pvscsi
Deleting directory tree below: /tmp/d20180619-3507-11ypihh/myCentOSBaseSCSI2
Completed with errors
#<Thread:0x000056485ac29428@/usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        20: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
        19: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
        18: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
        17: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
        16: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
        15: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
        14: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
        13: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
        12: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
        11: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
        10: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
         9: from /home2/scratch/xxxx/.vagrant.d/gems/2.5.1/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/esxi_password.rb:18:in `call'
         8: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
         7: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
         6: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
         5: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
         4: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
         3: from /home2/scratch/xxxx/.vagrant.d/gems/2.5.1/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/read_state.rb:64:in `call'
         2: from /usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
         1: from /home2/scratch/xxxx/.vagrant.d/gems/2.5.1/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/createvm.rb:18:in `call'
/home2/scratch/xxxx/.vagrant.d/gems/2.5.1/gems/vagrant-vmware-esxi-2.3.0/lib/vagrant-vmware-esxi/action/createvm.rb:112:in `createvm': There was an OVF Tool error. (VagrantPlugins::ESXi::Errors::OVFToolError)
  Unable to access myCentOSBaseSCSI2
There was an OVF Tool error.
  Unable to access myCentOSBaseSCSI2
```

### Tracking down the problem

running the ovftool command manually delivers the failure message from the subject: **Error: Invalid target disk adapter type: pvscsi**
```
#$ ovftool --noSSLVerify --overwrite --X:useMacNaming=false --powerOffTarget --noDisks --targetType=vmx --X:logLevel=info --X:logFile=/tmp/d20180619-3507-11ypihh/ovftool.log --acceptAllEulas vi://root:*******@esxi02/myCentOSBaseSCSI2 /tmp/d20180619-3507-11ypihh
Enter login information for source vi://192.168.0.12/
Username: root
Password: ***********
Opening VI source: vi://root@192.168.0.12:443/myCentOSBaseSCSI2
Opening VMX target: /tmp/d20180619-3507-11ypihh
Error: Invalid target disk adapter type: pvscsi
Deleting directory tree below: /tmp/d20180619-3507-11ypihh/myCentOSBaseSCSI2
Completed with errors
```

some more experiments
* Removing the --targetType=vmx option produces an .ovf package instead of an .vmx. In that case, there are no complaints by the ovftool about the target disk adapter.
* Using a base box where the OS disk is attached to the sata interface instead of the SCSI adapter works fine

### My Conclusion :-)
... it seems to be related to the disk adapters of the VM and the packaging format vmx.

1. Can somebody confirm this behavior? 
1. Is it an ovftool problem? Searching for the failure message brought up some old and some new reports, but nothing I could work with. It seems to be known but not sufficiently treated by VMWare/ovftool.
1. Should it be handled in `vagrant-vmware-esxi`? At least it is the default behavior of the solution, and as such ... some solution is needed. At least some documentation.
1. I now have a workaround for this problem (connecting the disk to the SATA interface), and just wanted to share it here

**Comment by josenk** [comment]
I believe this is clearly an ovftool problem.   There are many examples outside vagrant-vmware-esxi where this happens. 

VMWARE --->>>   It's really disappointing that your default option (Default SCSI controller type "VMware Paravirtual") which is your own device is not compatible with your own tool (ovftool) being exported to your own format (vmx)!!!   <<<--- 

Sorry, but I can't really use this work-around...   When doing a clone_from_vm I need a vmx file to read, so I cannot take away the --targetType=vmx option. 

Have you looked at logs that were generated by ovftool?   --X:logFile=/tmp/d20180619-3507-11ypihh/ovftool.log. 

You may want to consider using LSI SAS instead of SATA.  Here are some interesting articles on the subject...
>https://blogs.vmware.com/vsphere/2014/02/vscsi-controller-choose-performance.html
>https://www.virtualizationhowto.com/2017/07/vmware-lsi-sas-vs-pvscsi-vs-nvme-controller-performance/
>http://virtualguido.blogspot.com/2016/08/vmware-scsi-controller-options.html

**Comment by johnoooo** [comment]
I meant as workaround to configure another disk adapter. LSI SAS also looks good. Thanks for the hint and also thanks the links! For me, this issue can be closed and is documented by this report :-) 

Also: This is the output of the `ovftool`. Not sure whether it helps a lot, as it just lists the devices. 

```
2018-06-19T19:42:50.489+02:00 info OVFTool[11768] [Originator@6876 sub=Default] ReaderFactory web request: https://192.168.0.12/ha-nfc/52807614-cc4d-3ed2-07d0-13a96dd6f9af/disk-0.vmdk, noBody=true
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: 1 virtual CPU(s), InstanceId: 1, ResourceType: 3, ResourceSubType: 
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: CD-ROM 1, InstanceId: 10, ResourceType: 15, ResourceSubType: vmware.cdrom.atapi
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: Hard Disk 1, InstanceId: 11, ResourceType: 17, ResourceSubType: 
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: Ethernet 1, InstanceId: 12, ResourceType: 10, ResourceSubType: VmxNet3
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: 2048MB of memory, InstanceId: 2, ResourceType: 4, ResourceSubType: 
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: SATA Controller 0, InstanceId: 3, ResourceType: 20, ResourceSubType: vmware.sata.ahci
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: SCSI Controller 0, InstanceId: 4, ResourceType: 6, ResourceSubType: VirtualSCSI
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: USB Controller, InstanceId: 5, ResourceType: 23, ResourceSubType: vmware.usb.ehci
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: VirtualIDEController 1, InstanceId: 6, ResourceType: 5, ResourceSubType: 
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: VirtualIDEController 0, InstanceId: 7, ResourceType: 5, ResourceSubType: 
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: VirtualVideoCard, InstanceId: 8, ResourceType: 24, ResourceSubType: 
2018-06-19T19:42:50.908+02:00 info OVFTool[11768] [Originator@6876 sub=Default] [OvfConsumer]: ElementName: VirtualVMCIDevice, InstanceId: 9, ResourceType: 1, ResourceSubType: vmware.vmci

```
